stages:
  - mirror
  - test
  - stats
  - release

github_mirror:
  image: git
  stage: mirror
  tags: [ docker ]
  only: [ master, develop ]
  before_script:
    - echo "$GITHUB_SSH_KEY" > ~/.ssh/id_rsa
    - chmod 0600 ~/.ssh/id_rsa
  script:
    - git fetch
    - git checkout master
    - git pull
    - git push -f git@github.com:namboy94/manga-dl.git master
    - git checkout develop
    - git pull
    - git push -f git@github.com:namboy94/manga-dl.git develop

stylecheck:
  image: python:3.10
  stage: test
  tags: [ docker ]
  script:
    - pip install pycodestyle
    - pycodestyle manga_dl --max-line-length=120

type_check:
  image: python:3.10
  stage: test
  tags: [ docker ]
  script:
    - pip install mypy
    - mypy -p manga_dl --ignore-missing-imports --non-interactive --install-types

#unittest:
#  stage: test
#  tags: [ docker ]
#  script:
#    - python-unittest
#
#gitstats:
#  stage: stats
#  tags: [ docker ]
#  script:
#    - gitstats-gen
#
#docgen:
#  stage: stats
#  tags: [ docker ]
#  script:
#    - sphinx-docgen
#
#release_upload:
#  stage: release
#  only: [ master ]
#  tags: [ docker ]
#  script:
#    - github-release-upload $(cat version) "$(changelog-reader)"
#    - gitlab-release-upload $(cat version) "$(changelog-reader)"
#
#pypi_upload:
#  stage: release
#  only: [ master ]
#  tags: [ docker ]
#  script:
#    - pypi-upload
