stages:
  - mirror
  - test
  - release

github_mirror:
  image:
    name: alpine/git
    entrypoint: [ "" ]
  allow_failure: true
  stage: mirror
  tags: [ docker ]
  only: [ master, develop ]
  before_script:
    - mkdir ~/.ssh
    - echo "$GITHUB_SSH_KEY" > id_rsa
    - chmod 0600 id_rsa
    - ssh-keyscan -H github.com > known_hosts
    - git config --add --local core.sshCommand 'ssh -i id_rsa -o UserKnownHostsFile=known_hosts'
  script:
    - git fetch
    - git checkout master
    - git pull
    - git push -f git@github.com:namboy94/manga-dl.git master
    - git checkout develop
    - git pull
    - git push -f git@github.com:namboy94/manga-dl.git develop

stylecheck:
  image: python:3.10
  stage: test
  tags: [ docker ]
  script:
    - pip install pycodestyle
    - pycodestyle manga_dl --max-line-length=120

type_check:
  image: python:3.10
  stage: test
  tags: [ docker ]
  script:
    - pip install mypy
    - mypy -p manga_dl --ignore-missing-imports --non-interactive --install-types

unittest:
  image: python:3.10
  stage: test
  tags: [ docker ]
  script:
    - pip install .
    - python -m pytest

pypi_upload:
  image: python:3.10
  stage: release
  only: [ master ]
  tags: [ docker ]
  script:
    - pip install twine
    - python setup.py sdist
    - twine upload -u $PYPI_USERNAME -p $PYPY_PASSWORD dist/*
